name: hshh
description: An app for managing university sports activities
publish_to: 'none' 
version: 0.4.4+2

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  http: ^1.1.0
  lucide_icons: ^0.257.0
  html_character_entities: ^1.0.0+1
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  expand_widget: ^3.1.1
  transparent_image: ^2.0.1
  maps_launcher: ^2.2.0
  collection: ^1.17.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  flutter_inappwebview: ^5.8.0
  webview_flutter: ^4.4.2
  package_info: ^2.0.2
  countly_flutter: ^23.8.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  #flutter pub run flutter_oss_licenses:generate.dart
  flutter_launcher_icons: "^0.13.1"
  #flutter pub run flutter_launcher_icons

  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#B0DBFF"
  adaptive_icon_foreground: "assets/img/app_icon_adaptive.png"

flutter:
  assets:
    - assets/img/
  fonts:
    - family: Calistoga
      fonts:
        - asset: assets/fonts/Calistoga-Regular.ttf

  uses-material-design: true
  